//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapiexwithhttp3final
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int eid { get; set; }
        public string ename { get; set; }
        public Nullable<decimal> esal { get; set; }
        public Nullable<int> age { get; set; }
        public string position { get; set; }
    }
}
